; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
extra_scripts = post:../GenerateDisassembly.py
lib_deps = etlcpp/Embedded Template Library@^20.46.2
build_flags = 
	-Wall -Werror -g -O3
	-DAUGCSYNTH_CONFIG_SAMPLE_RATE=44100
	-DAUGCSYNTH_CONFIG_VOICE_POLYPHONY=6
	-DAUGCSYNTH_NO_STATE=1
